=== lcxWEB/studytest/src/main/resources/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="hr">
        <!--complexType-复杂节点，包含子节点时必须使用这个标签-->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="age">
                             <xs:simpleType>
                                 <xs:restriction base="xs:integer">
                                     <xs:minInclusive value="18"/>
                                     <xs:maxInclusive value="60"/>
                                 </xs:restriction>
                             </xs:simpleType>
                            </xs:element>
                            <xs:element name="salary" type="xs:integer"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="no" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lcxWEB/studytest/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<hr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test.xsd">
    <employee no="1111">
        <name>ddd</name>
        <age>45</age>
        <salary>999</salary>
    </employee>
    <employee no="3311">
        <name>莉莉</name>
        <age>17</age>
        <salary>3600</salary>
    </employee>
</hr>
